## Question Number 1

In [12]:
dataset = [
    (1, 2, 'A'),
    (2, 3, 'A'),
    (3, 3, 'A'),
    (6, 5, 'B'),
    (7, 7, 'B'),
    (8, 6, 'B')
]

def eDist(x1, y1, x2, y2):
    d=((x2 - x1)**2 + (y2 - y1)**2)
    return (d**0.5)

def KNN(dataset, test_x, test_y, k):
    distances = []
    for x, y, class_label in dataset:
        dist = eDist(test_x, test_y, x, y)
        distances.append((dist, x, y, class_label))
    
    # sorting 
    distances.sort(key=lambda x: x[0])

    selectedKNN = distances[:k]
    
    # Class labels of knn
    neighbor_classes = [neighbor[3] for neighbor in selectedKNN]
    
    class_counts = {}
    for class_label in neighbor_classes:
        if class_label in class_counts:
            class_counts[class_label] += 1
        else:
            class_counts[class_label] = 1
    
    predicted_class = max(class_counts, key=class_counts.get)
    return predicted_class, distances, selectedKNN

# test_x, test_y = 8, 7
test_x, test_y = 5, 4
k = 3

print(dataset)

print(f"\nTest Point: ({test_x}, {test_y})")
print(f"K value: {k}")

predicted_class, all_distances, k_nearest = KNN(dataset, test_x, test_y, k)
print(f"\nFinal Prediction: Class {predicted_class}")

[(1, 2, 'A'), (2, 3, 'A'), (3, 3, 'A'), (6, 5, 'B'), (7, 7, 'B'), (8, 6, 'B')]

Test Point: (5, 4)
K value: 3

Final Prediction: Class A


## Question Number 2

In [ ]:
import math

# Dataset (document, class)
dataset = [
    ("play football now", "Sports"),
    ("watch football game", "Sports"),
    ("join basketball practice", "Sports"),
    ("submit assignment", "Study"),
    ("study for exam", "Study"),
    ("read textbook chapter", "Study"),
    ("watch movie tonight", "Entertainment"),
    ("listen to music", "Entertainment"),
    ("play video games", "Entertainment"),
    ("attend online concert", "Entertainment"),
    ("football match highlights", "Sports"),
    ("prepare for math test", "Study")
]

test_docs = [
    "watch assignment",             #Document 1
    "watch soccer game",            #Document 2
    "submit assignment late"        #Document 3
]

In [ ]:
def create_vocabulary(dataset):
    vocab = set()
    for doc, label in dataset:
        words = doc.lower().split()
        vocab.update(words)
    return sorted(list(vocab))
l=create_vocabulary(dataset)
print(l)

['assignment', 'attend', 'basketball', 'chapter', 'concert', 'exam', 'football', 'for', 'game', 'games', 'highlights', 'join', 'listen', 'match', 'math', 'movie', 'music', 'now', 'online', 'play', 'practice', 'prepare', 'read', 'study', 'submit', 'test', 'textbook', 'to', 'tonight', 'video', 'watch']


1

In [ ]:
def create_vocabulary(dataset):
    vocab = set()
    for doc, label in dataset:
        words = doc.lower().split()
        vocab.update(words)
    return sorted(list(vocab))
l=create_vocabulary(dataset)
print(l)
BagOfWords = {}
for doc,label in dataset:
    words = doc.lower().split()
    for word in words:
        if word not in BagOfWords:
            BagOfWords[word] = len(BagOfWords)
print("Bag of Words Dictionary:")
print(BagOfWords)

Bag of Words Dictionary:
{'play': 0, 'football': 1, 'now': 2, 'watch': 3, 'game': 4, 'join': 5, 'basketball': 6, 'practice': 7, 'submit': 8, 'assignment': 9, 'study': 10, 'for': 11, 'exam': 12, 'read': 13, 'textbook': 14, 'chapter': 15, 'movie': 16, 'tonight': 17, 'listen': 18, 'to': 19, 'music': 20, 'video': 21, 'games': 22, 'attend': 23, 'online': 24, 'concert': 25, 'match': 26, 'highlights': 27, 'prepare': 28, 'math': 29, 'test': 30}


In [ ]:
def BOW_Vectors(document, vocabulary):
    words = document.lower().split()
    vector = []
    for word in vocabulary:
        vector.append(words.count(word))
    return vector
v=BOW_Vectors("watch soccer game game game", l)
print(v)

def manhattan_distance(vector1, vector2):
    return sum(abs(v1 - v2) for v1, v2 in zip(vector1, vector2))

[0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


In [ ]:

def knn_classify(train_vectors, trainingDataLabels, test_vector, k):
    distances = []
    
    for i, train_vector in enumerate(train_vectors):
        dist = manhattan_distance(test_vector, train_vector)
        distances.append((dist, trainingDataLabels[i], i))
    
    distances.sort(key=lambda x: x[0])
    k_nearest = distances[:k]
    
    class_votes = {}
    for dist, label, idx in k_nearest:
        if label in class_votes:
            class_votes[label] += 1
        else:
            class_votes[label] = 1
    
    predicted_class = max(class_votes, key=class_votes.get)
    
    return predicted_class, k_nearest, distances

In [ ]:

vocabulary = create_vocabulary(dataset)
print("Vocabulary:", vocabulary)
print(f"Vocabulary size: {len(vocabulary)}")

trainingDataDocs = [doc for doc, label in dataset]
trainingDataLabels = [label for doc, label in dataset]

print("\nTraining Document Vectors")
train_vectors = []
for i, doc in enumerate(trainingDataDocs):
    vector = BOW_Vectors(doc, vocabulary)
    train_vectors.append(vector)
    print(f"Doc {i+1}: '{doc}' -> {vector} [{trainingDataLabels[i]}]")

# Step 3: Convert test documents to BOW vectors
print("\nTest Document Vectors")
test_vectors = []
for i, test_doc in enumerate(test_docs):
    vector = BOW_Vectors(test_doc, vocabulary)
    test_vectors.append(vector)
    print(f"Test Doc {i+1}: '{test_doc}' -> {vector}")

Vocabulary: ['assignment', 'attend', 'basketball', 'chapter', 'concert', 'exam', 'football', 'for', 'game', 'games', 'highlights', 'join', 'listen', 'match', 'math', 'movie', 'music', 'now', 'online', 'play', 'practice', 'prepare', 'read', 'study', 'submit', 'test', 'textbook', 'to', 'tonight', 'video', 'watch']
Vocabulary size: 31

Training Document Vectors
Doc 1: 'play football now' -> [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [Sports]
Doc 2: 'watch football game' -> [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] [Sports]
Doc 3: 'join basketball practice' -> [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [Sports]
Doc 4: 'submit assignment' -> [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0] [Study]
Doc 5: 'study for exam' -> [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [ ]:

# Step 4: Apply KNN classification
k = 3
for i, test_vector in enumerate(test_vectors):
    
    predicted_class, k_nearest, all_distances = knn_classify(
        train_vectors, trainingDataLabels, test_vector, k
    )
    print(f"Predicted Class: {predicted_class}")    

Predicted Class: Study
Predicted Class: Sports
Predicted Class: Sports


## Question Number 3

In [66]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import math

iris = load_iris()
X = iris.data  # Features: sepal length, sepal width, petal length, petal width
y = iris.target  # Classes: 0=setosa, 1=versicolor, 2=virginica
class_names = iris.target_names

print(iris.feature_names)
print("classes = ",class_names)
print(f"Dataset shape: {X.shape}")

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
classes =  ['setosa' 'versicolor' 'virginica']
Dataset shape: (150, 4)


In [ ]:
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# print(X_train)
# print(X_test)
# print(y_train)
# print(y_test)

[[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [5.  3.2 1.

In [80]:
print(f"Training set size: {X_test.shape[0]}")

Training set size: 30


In [ ]:
def euclidean_distance(point1, point2):
    return math.sqrt(sum((p1 - p2)**2 for p1, p2 in zip(point1, point2)))
k = 5
print("value of k =",  k)

value of k = 5


In [ ]:
def knn_unweighted(X_train, y_train, test_point, k):
    distances = []
    for i, train_point in enumerate(X_train):
        dist = euclidean_distance(test_point, train_point)
        distances.append((dist, y_train[i], i))
    
    distances.sort(key=lambda x: x[0])
    k_nearest = distances[:k]
    
    # Count votes (unweighted)
    class_votes = {}
    for dist, label, idx in k_nearest:
        if label in class_votes:
            class_votes[label] += 1
        else:
            class_votes[label] = 1
    
    predicted_class = max(class_votes, key=class_votes.get)
    return predicted_class, k_nearest

In [ ]:
def knn_weighted(X_train, y_train, test_point, k):
    distances = []
    
    for i, train_point in enumerate(X_train):
        dist = euclidean_distance(test_point, train_point)
        distances.append((dist, y_train[i], i))
    
    distances.sort(key=lambda x: x[0])
    k_nearest = distances[:k]
    
    class_votes = {}
    for dist, label, idx in k_nearest:
        weight = 1.0 / (dist + 1e-8)  # Add small epsilon to avoid division by zero 
        
        if label in class_votes:
            class_votes[label] += weight
        else:
            class_votes[label] = weight
    
    # Find class with highest weighted vote
    predicted_class = max(class_votes, key=class_votes.get)
    return predicted_class, k_nearest

In [ ]:

unweighted_predictions = []
weighted_predictions = []
for i, test_point in enumerate(X_test):
    # Unweighted KNN
    pred_unweighted, _ = knn_unweighted(X_train, y_train, test_point, k)
    unweighted_predictions.append(pred_unweighted)
    
    # Weighted KNN
    pred_weighted, _ = knn_weighted(X_train, y_train, test_point, k)
    weighted_predictions.append(pred_weighted)
    
    # Show first 10 predictions
    if i < X_test.shape[0]:
        true_class = class_names[y_test[i]]
        unweighted_class = class_names[pred_unweighted]
        weighted_class = class_names[pred_weighted]
        print(f"{i+1:4d} ,  {true_class} ,  {unweighted_class}  ,  {weighted_class}")

   1 ,  versicolor ,  versicolor  ,  versicolor
   2 ,  setosa ,  setosa  ,  setosa
   3 ,  virginica ,  virginica  ,  virginica
   4 ,  versicolor ,  versicolor  ,  versicolor
   5 ,  versicolor ,  versicolor  ,  versicolor
   6 ,  setosa ,  setosa  ,  setosa
   7 ,  versicolor ,  versicolor  ,  versicolor
   8 ,  virginica ,  virginica  ,  virginica
   9 ,  versicolor ,  versicolor  ,  versicolor
  10 ,  versicolor ,  versicolor  ,  versicolor
  11 ,  virginica ,  virginica  ,  virginica
  12 ,  setosa ,  setosa  ,  setosa
  13 ,  setosa ,  setosa  ,  setosa
  14 ,  setosa ,  setosa  ,  setosa
  15 ,  setosa ,  setosa  ,  setosa
  16 ,  versicolor ,  versicolor  ,  versicolor
  17 ,  virginica ,  virginica  ,  virginica
  18 ,  versicolor ,  versicolor  ,  versicolor
  19 ,  versicolor ,  versicolor  ,  versicolor
  20 ,  virginica ,  virginica  ,  virginica
  21 ,  setosa ,  setosa  ,  setosa
  22 ,  virginica ,  virginica  ,  virginica
  23 ,  setosa ,  setosa  ,  setosa
  24 ,  vi

In [ ]:

# Calculate accuracy
unweighted_accuracy = sum(1 for true, pred in zip(y_test, unweighted_predictions) if true == pred) / len(y_test)
weighted_accuracy = sum(1 for true, pred in zip(y_test, weighted_predictions) if true == pred) / len(y_test)

print(unweighted_accuracy)
print(weighted_accuracy)

1.0
1.0
