## TASK 1

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = np.array([
    [1,2.1],[2,2.5],[1.5,2.3],[3,2.9],[2.2,2.6],[8,3.8],[7.5,3.6],[9,3.9],[7,3.5],[8.5,3.7],
    [3.2,3.1],[2.8,2.8],[6,3.2],[6.5,3.3],[4,3.0],[5.5,3.4],[3.8,3.1],[4.2,3.2],[5,3.3],[6.8,3.4]])

In [12]:
print(data.shape[0])

20


In [14]:
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

In [ ]:
# You are given a dataset of 20 students with Study Hours and CGPA.
# Your goal is to apply K-Means clustering (K = 2) and group students into 2 categories based on
# performance patterns.
# You must:
# 1. Initialize centroids manually (random 2 points from dataset)

k=2
centroids = np.array([data[5], data[15]])
print("Initial Centroids:\n", centroids)

# 2. Calculate distance of each point from centroids (Euclidean distance)
shape=data.shape[0]
distances = np.zeros((shape, k)) # k # of clusters used for distance storage to each centroid
for i in range(shape):
    for j in range(k):
        distances[i][j] = euclidean_distance(data[i], centroids[j])
print("\n\nDistances from Centroids:\n", distances)

# 3. Assign each point to the nearest cluster
cluster_assignments = np.argmin(distances, axis=1)
print("\n\nCluster Assignments:\n", cluster_assignments)


# 4. Update centroids by averaging points in each cluster
# 5. Repeat steps 2–4 until cluster assignments do not change (convergence)
updatedCentroids = np.zeros((k, data.shape[1]))
while True:
    for j in range(k): # 
        ClusterPoint = data[cluster_assignments == j]   
        if len(ClusterPoint) > 0:
            updatedCentroids[j] = np.mean(ClusterPoint, axis=0)

    distances = np.zeros((shape, k)) # Reset distances for new calculation
    for i in range(shape):
        for j in range(k):
            distances[i][j] = euclidean_distance(data[i], updatedCentroids[j])
    new_cluster_assignments = np.argmin(distances, axis=1)

    if np.array_equal(cluster_assignments, new_cluster_assignments):
        break
    cluster_assignments = new_cluster_assignments
    centroids = updatedCentroids.copy()
print("\n\nFinal Cluster Assignments:\n", cluster_assignments)
print("\nFinal Centroids:\n", updatedCentroids)


Initial Centroids:
 [[8.  3.8]
 [5.5 3.4]]


Distances from Centroids:
 [[7.20347139 4.68401537]
 [6.13921819 3.6138622 ]
 [6.67083203 4.1484937 ]
 [5.08035432 2.54950976]
 [5.92283716 3.39558537]
 [0.         2.53179778]
 [0.53851648 2.00997512]
 [1.00498756 3.53553391]
 [1.04403065 1.50332964]
 [0.50990195 3.01496269]
 [4.85077313 2.3194827 ]
 [5.29528092 2.76586334]
 [2.0880613  0.53851648]
 [1.58113883 1.00498756]
 [4.07921561 1.55241747]
 [2.53179778 0.        ]
 [4.25793377 1.72626765]
 [3.84707681 1.31529464]
 [3.04138127 0.50990195]
 [1.26491106 1.3       ]]


Cluster Assignments:
 [1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0]


Final Cluster Assignments:
 [1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 1 1 1 0]

Final Centroids:
 [[7.2        3.53333333]
 [2.97272727 2.80909091]]


## TASK 2

In [37]:
docs = [
"AI improves healthcare systems",
"Machine learning models evolve",
"Technology is changing education",
"Deep learning achieves accuracy",
"Computers process data fast",
"Robots assist in industries",
"Football players train daily",
"Cricket match was exciting",
"The team won the tournament",
"Athletes need physical training",
"Basketball is a popular sport",
"Stadium crowd cheered loudly",
]

In [ ]:
docs = [
"AI improves healthcare systems",
"Machine learning models evolve",
"Technology is changing education",
"Deep learning achieves accuracy",
"Computers process data fast",
"Robots assist in industries",
"Football players train daily",
"Cricket match was exciting",
"The team won the tournament",
"Athletes need physical training",
"Basketball is a popular sport",
"Stadium crowd cheered loudly",
]

vocab = set()
for doc in docs:
    for word in doc.lower().split():
        vocab.add(word)
print("\n\nVocabulary Length:\n", len(vocab))
print("\nVocabulary:\n", vocab)

def BagOfWords(docs,vocab):
    bow_matrix = np.zeros((len(docs), len(vocab)), dtype=int)
    for i, doc in enumerate(docs):
        words = doc.lower().split()
        for j, word in enumerate(vocab):
            bow_matrix[i][j] = words.count(word)
    return bow_matrix
bow = BagOfWords(docs,vocab)
print("\n\nBag of Words Matrix:\n", bow)



Vocabulary Length:
 47

Vocabulary:
 {'athletes', 'cricket', 'match', 'players', 'process', 'models', 'sport', 'was', 'in', 'tournament', 'stadium', 'loudly', 'robots', 'ai', 'train', 'exciting', 'basketball', 'need', 'learning', 'crowd', 'systems', 'data', 'technology', 'industries', 'fast', 'computers', 'football', 'achieves', 'healthcare', 'evolve', 'improves', 'the', 'changing', 'popular', 'accuracy', 'daily', 'won', 'machine', 'education', 'assist', 'physical', 'deep', 'is', 'team', 'cheered', 'training', 'a'}


Bag of Words Matrix:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0
  0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0

In [70]:
k=2
cluster1="Tech and AI Topics"
cluster2="Sports Topics"


# Compute similarity between documents (Euclidean distance on vectors)
def euclidean_distance2(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2))

centroids = np.array([bow[0], bow[1]])  # Initialize centroids with first Tech and first Sports doc
shape=bow.shape[0]
distances = np.zeros((shape, k))  # Distance storage

# Calculating initial distances and assignments
for i in range(shape):
    for j in range(k):
        distances[i][j] = euclidean_distance2(bow[i], centroids[j])
cluster_assignments = np.argmin(distances, axis=1)
updatedCentroids = np.zeros((k, bow.shape[1]))


while True:
    for j in range(k):  # For each cluster
        ClusterPoint = bow[cluster_assignments == j]
        if len(ClusterPoint) > 0:
            updatedCentroids[j] = np.mean(ClusterPoint, axis=0)

    distances = np.zeros((shape, k))  # Reset distances
    for i in range(shape):
        for j in range(k):
            distances[i][j] = euclidean_distance2(bow[i], updatedCentroids[j])
    new_cluster_assignments = np.argmin(distances, axis=1)

    if np.array_equal(cluster_assignments, new_cluster_assignments):
        break
    cluster_assignments = new_cluster_assignments
    centroids = updatedCentroids.copy()


print("\n\nFinal Document Cluster Assignments:\n", cluster_assignments)
for i, assignment in enumerate(cluster_assignments):
    topic = cluster1 if assignment == 0 else cluster2
    print(f"Document {i}: {topic}")




Final Document Cluster Assignments:
 [0 1 0 1 0 0 0 0 0 0 0 0]
Document 0: Tech and AI Topics
Document 1: Sports Topics
Document 2: Tech and AI Topics
Document 3: Sports Topics
Document 4: Tech and AI Topics
Document 5: Tech and AI Topics
Document 6: Tech and AI Topics
Document 7: Tech and AI Topics
Document 8: Tech and AI Topics
Document 9: Tech and AI Topics
Document 10: Tech and AI Topics
Document 11: Tech and AI Topics


## TASK 3

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.cluster import KMeans

 
# 1. Load Dataset
data = pd.DataFrame({
    "Age":[22,25,31,29,35,41,38,26,30,40,23,28,36,45,27],
    "Income":[35,40,52,48,60,72,69,45,50,70,38,46,62,80,44],
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female","Female","Male","Female","Male","Male"],
    "City":["A","B","A","C","B","A","C","A","B","C","B","A","B","C","A"]
})

print("\nOriginal Data:")
print(data)

 
# 2. One-Hot Encode Categorical Features
encoder = OneHotEncoder(drop='first', sparse_output=False)
cat_features = encoder.fit_transform(data[["Gender", "City"]])

cat_df = pd.DataFrame(cat_features, columns=encoder.get_feature_names_out(["Gender", "City"]))
print("\nOne-Hot Encoded Features:")
print(cat_df)

 
# 3. Scale Numeric Data
scaler = StandardScaler()
num_scaled = scaler.fit_transform(data[["Age", "Income"]])
num_df = pd.DataFrame(num_scaled, columns=["Age_scaled", "Income_scaled"])

print("\nScaled Numeric Features:")
print(num_df)

 
# 4. Combine Processed Data
final_data = pd.concat([num_df, cat_df], axis=1)
print("\nFinal Data Used for K-Means:")
print(final_data)

 
# 5. Apply K-Means (k = 3)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(final_data)
data["Cluster"] = clusters

print("\nCluster Assignments:")
print(data)

 
# 6. Analyze Cluster Patterns
 
cluster_summary = data.groupby("Cluster")[["Age", "Income"]].mean()
print("\nCluster Summary (Mean Age & Income):")
print(cluster_summary)


#cluster 0 => young and med income
#cluster 1 => v young and Low income
#cluster 2 => older and high income


Original Data:
    Age  Income  Gender City
0    22      35    Male    A
1    25      40  Female    B
2    31      52    Male    A
3    29      48  Female    C
4    35      60    Male    B
5    41      72  Female    A
6    38      69    Male    C
7    26      45  Female    A
8    30      50    Male    B
9    40      70  Female    C
10   23      38  Female    B
11   28      46    Male    A
12   36      62  Female    B
13   45      80    Male    C
14   27      44    Male    A

One-Hot Encoded Features:
    Gender_Male  City_B  City_C
0           1.0     0.0     0.0
1           0.0     1.0     0.0
2           1.0     0.0     0.0
3           0.0     0.0     1.0
4           1.0     1.0     0.0
5           0.0     0.0     0.0
6           1.0     0.0     1.0
7           0.0     0.0     0.0
8           1.0     1.0     0.0
9           0.0     0.0     1.0
10          0.0     1.0     0.0
11          1.0     0.0     0.0
12          0.0     1.0     0.0
13          1.0     0.0     1.0
14          1